'use client';
import { useEffect,useState,useRef } from 'react';
import { flushSync } from 'react-dom';
import { ShoppingBag, Plus,Minus,ArrowUpRight,ArrowRight,MessageCircle,X,Leaf,Check,ChevronLeft,ChevronRight } from 'lucide-react';
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { type Product,money,lineTotal } from '@/lib/catalog';
export default function Storefront({products,phone}:{products:Product[];phone:string}){
 const [cart,setCart]=useState<Record<string,number>>({}),[ready,setReady]=useState(false),[cartOpen,setCartOpen]=useState(false),[selected,setSelected]=useState<Product|null>(null),[photo,setPhoto]=useState(0),[quantity,setQuantity]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('nani-cart')||'{}');const valid:Record<string,number>={};for(const p of products){const q=saved[p.id];if(Number.isInteger(q)&&q>0&&q<=99)valid[p.id]=q;}setCart(valid);}catch{}setReady(true);},[products]);
 useEffect(()=>{if(ready)localStorage.setItem('nani-cart',JSON.stringify(cart));},[cart,ready]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3000);return()=>clearTimeout(t);},[notice]);
 const agentState=useRef({products,cart});agentState.current={products,cart};
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.error);}catch(e){console.error(e);}};register({name:'read_nani_catalog',description:'Read available products, prices and staged cart. Does not send an order.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>agentState.current});register({name:'stage_nani_cart',description:'Set quantities for products in the visible cart. Quantity zero removes a product. Does not open WhatsApp or send a message.',inputSchema:{type:'object',properties:{items:{type:'array',maxItems:100,items:{type:'object',properties:{id:{type:'string'},quantity:{type:'integer',minimum:0,maximum:99}},required:['id','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const value=input as {items?:{id:string;quantity:number}[]};if(!value||!Array.isArray(value.items)||value.items.length>100||value.items.some(i=>!i||!agentState.current.products.some(p=>p.id===i.id)||!Number.isInteger(i.quantity)||i.quantity<0||i.quantity>99))throw new Error('Invalid product or quantity');const next={...agentState.current.cart};for(const i of value.items){if(i.quantity)next[i.id]=i.quantity;else delete next[i.id];}flushSync(()=>{setCart(next);setCartOpen(true);});return {cart:next,status:'staged'};}});return()=>lifecycle.abort();},[]);
 const items=products.filter(p=>cart[p.id]).map(product=>({product,quantity:cart[product.id]}));const count=items.reduce((n,i)=>n+i.quantity,0),total=items.reduce((n,i)=>n+lineTotal(i.product,i.quantity),0);
 function add(p:Product,q=1){setCart(c=>({...c,[p.id]:Math.min(99,(c[p.id]||0)+q)}));setNotice(`${p.name} se agregó a tu carrito`);setError('');}
 function change(id:string,q:number){setCart(c=>{const next={...c};if(q<=0)delete next[id];else next[id]=Math.min(99,q);return next;});setError('');}
 function open(p:Product){setSelected(p);setPhoto(0);setQuantity(1);}
 async function checkout(){setBusy(true);setError('');try{const response=await fetch('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(items.map(i=>({id:i.product.id,quantity:i.quantity})))});const data=await response.json() as {error?:string;url:string;items:{product:Product;quantity:number}[]};if(!response.ok)throw new Error(data.error);if(data.items.some((i:{product:Product;quantity:number})=>lineTotal(i.product,i.quantity)!==lineTotal(products.find(p=>p.id===i.product.id)!,i.quantity)))throw new Error('Se actualizaron los precios. Recargá el catálogo para revisar el total antes de enviar.');window.location.assign(data.url);}catch(e){setError(e instanceof Error?e.message:'No pudimos armar el pedido. Intentá nuevamente.');}finally{setBusy(false);}}
 return <><div className="announcement">Alma, corazón & vida <span>·</span> Detalles que hacen hogar</div><header className="site-header"><a href="/" aria-label="NANI, inicio" className="brand"><img src="/images/logo-white.webp" alt="NANI"/></a><nav><a href="#coleccion">La colección</a><a href={`https://wa.me/${phone}`} target="_blank" rel="noreferrer">Hablemos <ArrowUpRight size={15}/></a></nav><button className="cart-button" onClick={()=>setCartOpen(true)}><ShoppingBag size={20}/><span>Tu carrito</span><b>{count}</b></button></header>
 <main><section className="hero"><div className="hero-copy"><p className="eyebrow">NATURALMENTE, NANI</p><h1>Un rincón.<br/>Un detalle.<br/><em>Todo cambia.</em></h1><p className="hero-description">Texturas que abrazan y piezas con alma.<br/>Encontrá eso que hace de tu casa, tu lugar.</p><a className="button dark" href="#coleccion">Explorá la colección <ArrowRight size={18}/></a><div className="hero-foot"><span className="tiny-line"/> MACRAMÉ · TEXTURAS · CALIDEZ</div></div><div className="hero-visual"><img src="/images/aloja-2.webp" alt="Pantallas de macramé Aloja entre hojas verdes" fetchPriority="high"/><div className="image-caption"><span>Fibras naturales.<br/><em>Espacios con alma.</em></span><span className="image-number">01 / NANI</span></div><div className="round-stamp">alma,<br/><em>corazón</em><br/>& vida</div></div></section>
 <section className="collection" id="coleccion"><div className="section-heading"><div><p className="eyebrow">LA COLECCIÓN</p><h2>Tramas que enamoran.</h2></div><p>Pantallas de macramé<br/><span>Elegí la que va con vos.</span></p></div><div className="collection-rule"><span><Leaf size={15}/> Textura natural, carácter propio</span><span>{products.length} {products.length===1?'pieza':'piezas'}</span></div><div className="product-grid">{products.map((p,index)=><article className="product-card" key={p.id}><button className="product-image" onClick={()=>open(p)} aria-label={`Ver Pantalla ${p.name}`}><img src={p.images[0]} alt={`Pantalla ${p.name}`} loading="lazy"/><span className="product-index">0{index+1}</span>{p.pairPrice&&<span className="promo-tag">Llevá 2, pagá menos</span>}<span className="view-product">Descubrila <ArrowUpRight size={18}/></span></button><div className="product-meta"><p>PANTALLA DE MACRAMÉ</p><span>Ø {p.diameter}</span></div><div className="product-title"><button onClick={()=>open(p)}><h3>{p.name}</h3></button><p>{money(p.price)}</p></div><p className="pair-price">{p.pairPrice?<>Llevando 2: <strong>{money(p.pairPrice)} c/u</strong></>:<>Una pieza para tu rincón favorito.</>}</p><button className="add-button" onClick={()=>add(p)}>Agregar al carrito <Plus size={18}/></button></article>)}</div>{!products.length&&<div className="empty"><h3>Estamos preparando nuevas piezas.</h3><p>Escribinos para conocer las próximas novedades.</p></div>}</section>
 <section className="closing"><div className="closing-mark"><Leaf size={28} strokeWidth={1}/></div><h2>Lo simple también<br/>puede ser <em>extraordinario.</em></h2><div><p>Elegí tus favoritos, armá tu carrito<br/>y coordinamos los detalles por WhatsApp.</p><a href={`https://wa.me/${phone}`} target="_blank" rel="noreferrer">Estamos del otro lado <ArrowUpRight size={18}/></a></div></section></main><footer><a className="brand" href="/" aria-label="Inicio NANI"><img src="/images/logo-white.webp" alt="NANI"/></a><p>ALMA, CORAZÓN & VIDA</p><div><a href="https://www.instagram.com/Nani.Deco.Tuc/" target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={14}/></a><a href="/admin">Administrar</a></div></footer>
 <div aria-live="polite" className={notice?'toast':'sr-only'}>{notice&&<Check size={18}/>} {notice}</div>
 <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-sheet" showCloseButton={false}><div className="panel-heading"><div><p className="eyebrow">TUS ELEGIDOS</p><SheetTitle className="panel-title">Tu carrito <small>({count})</small></SheetTitle></div><button className="icon-button" onClick={()=>setCartOpen(false)} aria-label="Cerrar carrito"><X/></button></div><SheetDescription className="panel-description">Un poquito más cerca de ese rincón que imaginás.</SheetDescription><div className="cart-items">{items.map(({product:p,quantity:q})=><div className="cart-item" key={p.id}><img src={p.images[0]} alt={p.name}/><div><span className="small-label">PANTALLA · Ø {p.diameter}</span><h3>{p.name}</h3><p>{money(lineTotal(p,q))}</p>{p.pairPrice&&q>=2&&<small className="discount-label">Promo por pares aplicada</small>}<div className="quantity-control"><button aria-label={`Quitar una ${p.name}`} onClick={()=>change(p.id,q-1)}><Minus size={14}/></button><span>{q}</span><button disabled={q>=99} aria-label={`Sumar una ${p.name}`} onClick={()=>change(p.id,q+1)}><Plus size={14}/></button></div></div><button className="remove-button" aria-label={`Eliminar ${p.name}`} onClick={()=>change(p.id,0)}><X size={16}/></button></div>)}{!items.length&&<div className="empty"><ShoppingBag size={40} strokeWidth={1}/><h3>Tu próximo detalle<br/>está por acá.</h3><p>Todavía no agregaste productos.</p><button className="button dark" onClick={()=>setCartOpen(false)}>Seguir explorando</button></div>}</div>{!!items.length&&<div className="cart-bottom"><div className="total"><span>Total de productos</span><strong>{money(total)}</strong></div><p>Entrega y forma de pago a coordinar. Las pantallas no incluyen instalación eléctrica.</p>{error&&<p role="alert" className="error">{error} <a href="/">Recargar catálogo</a></p>}<button disabled={busy} className="button whatsapp" onClick={checkout}><MessageCircle size={19}/>{busy?'Preparando pedido…':'Finalizar por WhatsApp'}<ArrowUpRight size={18}/></button><small>Se abrirá WhatsApp con tu pedido listo para enviar.</small></div>}</SheetContent></Sheet>
 <Sheet open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><SheetContent className="detail-sheet" showCloseButton={false}>{selected&&<><div className="panel-heading"><SheetTitle className="panel-title">Pantalla {selected.name}</SheetTitle><button className="icon-button" aria-label="Cerrar producto" onClick={()=>setSelected(null)}><X/></button></div><SheetDescription className="sr-only">Fotos y detalles de Pantalla {selected.name}</SheetDescription><div className="detail-scroll"><div className="detail-photo"><img src={selected.images[photo]} alt={`${selected.name}, foto ${photo+1}`}/>{selected.images.length>1&&<><button className="photo-prev" aria-label="Foto anterior" onClick={()=>setPhoto((photo+selected.images.length-1)%selected.images.length)}><ChevronLeft/></button><button className="photo-next" aria-label="Foto siguiente" onClick={()=>setPhoto((photo+1)%selected.images.length)}><ChevronRight/></button></>}</div><div className="thumbnails">{selected.images.map((im,i)=><button key={im} className={i===photo?'active':''} onClick={()=>setPhoto(i)} aria-label={`Ver foto ${i+1}`}><img src={im} alt=""/></button>)}</div><div className="detail-copy"><p className="eyebrow">{selected.code} · Ø {selected.diameter}</p><h2>{selected.name}</h2><p>{selected.description}</p><p className="detail-price">{money(selected.price)}</p>{selected.pairPrice&&<div className="promo-note">Llevando 2 del mismo modelo: <strong>{money(selected.pairPrice)} c/u.</strong><br/><small>La promoción se aplica por cada par. Una unidad extra lleva precio individual.</small></div>}<div className="detail-action"><div className="quantity-control"><button disabled={quantity<=1} aria-label="Reducir cantidad" onClick={()=>setQuantity(q=>q-1)}><Minus size={16}/></button><span>{quantity}</span><button disabled={quantity>=99} aria-label="Aumentar cantidad" onClick={()=>setQuantity(q=>q+1)}><Plus size={16}/></button></div><button className="button dark" onClick={()=>{add(selected,quantity);setSelected(null);setCartOpen(true)}}>Agregar · {money(lineTotal(selected,quantity))}<Plus size={18}/></button></div></div></div></>}</SheetContent></Sheet></>;
}
